name: sitebuilder
channels: !!python/tuple
- conda-forge
- bioconda
- r
- defaults
dependencies:
- conda-forge::certifi=2016.9.26=py35_0
- conda-forge::pip=9.0.1=py35_0
- conda-forge::python=3.5.2=2
- conda-forge::setuptools=32.1.0=py35_0
- conda-forge::vs2015_runtime=14.0.25420=0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::wincertstore=0.2=py35_0
- pip:
  - csscompressor==0.9.4
  - wrapt==1.10.8
